### ISSUE TITLE
RewrapException

### ISSUE THREAD

**Issue by irisoer** [usadson/VraagEenPro#16]
In mijn branch (Iris2) als ik de applicatie opstart krijg ik een RewrapException, dit is zo sinds ik de branches van natalie en jonathan heb semengevoegd. Ik heb geen idee waarom dit gebeurt. Moet ik maandag even naar kijken of ik hier uit kan komen. Of als een van jullie een idee heeft hoor ik het graag. Lijkt of er iets lokaal in mijn folders mist.

**Comment by usadson** [comment]
Fixed
